name: green_gym_club
description: "Green Gym Club"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.0
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_fortune_wheel: ^1.3.2
  toast: ^0.3.0
  flutter_flip_card: ^0.0.6
  google_fonts: ^6.2.1
  text_gradiate: ^1.0.1
  gradient_borders: ^1.0.2
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.2.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: assets/fonts/otomanopee_one_regular.ttf

