name: green_gym_club
description: "Green Gym Club"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.0
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_flip_card: ^0.0.6
  google_fonts: ^6.2.1
  text_gradiate: ^1.0.1
  gradient_borders: ^1.0.2
  flutter_switch: ^0.3.2
  onboarding: ^4.0.2
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  vibration: ^2.1.0
  audioplayers: ^6.5.1
  flutter_inappwebview: ^6.1.5
  toast: ^0.3.0
  http: ^1.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^11.5.0
  url_launcher: ^6.3.2
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  firebase_messaging: ^15.2.8
  firebase_core: ^3.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^9.2.0
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/launcher_icon/
    - assets/images/
    - assets/sounds/
    - assets/music/

  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: assets/fonts/otomanopee_one_regular.ttf

